version: '3'

services:
  database:
    container_name: database
    image: postgres:latest
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      - SERVER_PORT=80
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
    volumes:
      - .:/app
    depends_on:
      - database
        
volumes:
  postgres_data: