DROP INDEX IF EXISTS "idx_users_role_id";
DROP INDEX IF EXISTS "idx_users_referer_id";
DROP INDEX IF EXISTS "idx_config_user_id";
DROP INDEX IF EXISTS "idx_configs_server_id";
DROP INDEX IF EXISTS "idx_referals_referee_id";
DROP INDEX IF EXISTS "idx_referee_referals_id";
DROP INDEX IF EXISTS "idx_payments_user_id";
DROP INDEX IF EXISTS "idx_servers_location";
DROP INDEX IF EXISTS "idx_server_credentials_server_id";