CREATE TABLE "users" (
  "telegram_id" bigint PRIMARY KEY,
  "username" varchar(128),
  "role_id" bigint NOT NULL,
  "balance" money DEFAULT 0,
  "referer_id" bigint,
  "birth_date" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "roles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(128) UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "configs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "server_id" bigint NOT NULL,
  "vless_link" text UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "vpn_clients" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(128) UNIQUE NOT NULL,
  "download_link" text,
  "os" enum(windows,macos,linux,android,ios),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "referals" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "referee_id" bigint,
  "referal_id" bigint,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "transactions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "amount" money NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "subcription_types" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(128) UNIQUE NOT NULL,
  "devices_count" int NOT NULL,
  "price" money NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "subcriptions" (
  "id" bigint PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "subscription_type_id" bigint NOT NULL,
  "activated_at" timestamp DEFAULT (now()),
  "expires_at" timestamp NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "servers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(128) UNIQUE NOT NULL,
  "ip_address" varchar(45) NOT NULL,
  "location" varchar(128),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "server_credentials" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "server_id" bigint UNIQUE NOT NULL,
  "password" varchar(256) NOT NULL,
  "public_key" text NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);